default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tooldrawer
  host: localhost

test:
  <<: *default
  database: tooldrawer
  host: localhost
